import type { ThemeConfig, ThemeId } from '@mdxstudio/core';

/*
 * Font stacks, spelled out rather than named through a framework's variables.
 * These are the exact stacks the utility classes resolved to, so a preset looks
 * the same whether or not the host has Tailwind.
 */
const SANS =
  '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", "Noto Sans", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"';
const SERIF = 'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif';
const MONO =
  'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace';

export const THEMES: Record<ThemeId, ThemeConfig> = {
  'frosted-glass': {
    id: 'frosted-glass',
    name: 'Frosted Glass',
    category: 'dark',
    fontFamily: 'font-sans',
    bgClass: 'bg-slate-900/60 backdrop-blur-xl',
    textClass: 'text-slate-100',
    headingClass: 'text-white border-b border-white/10',
    cardBgClass: 'bg-white/10 backdrop-blur-lg border-white/20 shadow-xl',
    borderClass: 'border-white/15',
    codeBgClass: 'bg-slate-950/80 backdrop-blur-md',
    codeTextClass: 'text-cyan-300',
    accentClass: 'text-indigo-400',
    primaryButtonClass: 'bg-indigo-600/80 hover:bg-indigo-500/90 backdrop-blur-md text-white shadow-lg shadow-indigo-500/20 border border-indigo-400/30',
    badgeClass: 'bg-indigo-500/20 text-indigo-300 border-indigo-400/30 backdrop-blur-md',
    previewBg: 'rgba(15, 23, 42, 0.85)',
    previewText: '#f8fafc',
    cssVars: {
      '--mdxkit-font-body': SANS,
      '--mdxkit-surface-backdrop-filter': 'blur(24px)',
      '--mdxkit-heading-fg': '#fff',
      '--mdxkit-heading-border': 'color-mix(in oklab, #fff 10%, transparent)',
      '--mdxkit-link-fg': 'oklch(67.3% 0.182 276.935)',
      '--mdxkit-inline-code-bg': 'color-mix(in oklab, oklch(12.9% 0.042 264.695) 80%, transparent)',
      '--mdxkit-inline-code-fg': 'oklch(86.5% 0.127 207.078)',
      '--mdxkit-inline-code-backdrop-filter': 'blur(12px)',
    },
  },
  'github-light': {
    id: 'github-light',
    name: 'GitHub Light',
    category: 'light',
    fontFamily: 'font-sans',
    bgClass: 'bg-white',
    textClass: 'text-slate-800',
    headingClass: 'text-slate-900 border-b border-slate-200',
    cardBgClass: 'bg-slate-50 border-slate-200',
    borderClass: 'border-slate-200',
    codeBgClass: 'bg-slate-100',
    codeTextClass: 'text-slate-900',
    accentClass: 'text-blue-600',
    primaryButtonClass: 'bg-blue-600 hover:bg-blue-700 text-white',
    badgeClass: 'bg-blue-100 text-blue-800 border-blue-200',
    previewBg: '#ffffff',
    previewText: '#1e293b',
    cssVars: {
      '--mdxkit-font-body': SANS,
      '--mdxkit-heading-fg': 'oklch(20.8% 0.042 265.755)',
      '--mdxkit-heading-border': 'oklch(92.9% 0.013 255.508)',
      '--mdxkit-link-fg': 'oklch(54.6% 0.245 262.881)',
      '--mdxkit-inline-code-bg': 'oklch(96.8% 0.007 247.896)',
      '--mdxkit-inline-code-fg': 'oklch(20.8% 0.042 265.755)',
    },
  },
  'github-dark': {
    id: 'github-dark',
    name: 'GitHub Dark',
    category: 'dark',
    fontFamily: 'font-sans',
    bgClass: 'bg-slate-950',
    textClass: 'text-slate-200',
    headingClass: 'text-white border-b border-slate-800',
    cardBgClass: 'bg-slate-900 border-slate-800',
    borderClass: 'border-slate-800',
    codeBgClass: 'bg-slate-900',
    codeTextClass: 'text-emerald-400',
    accentClass: 'text-blue-400',
    primaryButtonClass: 'bg-blue-600 hover:bg-blue-500 text-white',
    badgeClass: 'bg-blue-950 text-blue-300 border-blue-800',
    previewBg: '#020617',
    previewText: '#e2e8f0',
    cssVars: {
      '--mdxkit-font-body': SANS,
      '--mdxkit-heading-fg': '#fff',
      '--mdxkit-heading-border': 'oklch(27.9% 0.041 260.031)',
      '--mdxkit-link-fg': 'oklch(70.7% 0.165 254.624)',
      '--mdxkit-inline-code-bg': 'oklch(20.8% 0.042 265.755)',
      '--mdxkit-inline-code-fg': 'oklch(76.5% 0.177 163.223)',
    },
  },
  dracula: {
    id: 'dracula',
    name: 'Dracula',
    category: 'dark',
    fontFamily: 'font-sans',
    bgClass: 'bg-[#282a36]',
    textClass: 'text-[#f8f8f2]',
    headingClass: 'text-[#ff79c6] border-b border-[#44475a]',
    cardBgClass: 'bg-[#1e1f29] border-[#44475a]',
    borderClass: 'border-[#44475a]',
    codeBgClass: 'bg-[#191a21]',
    codeTextClass: 'text-[#50fa7b]',
    accentClass: 'text-[#bd93f9]',
    primaryButtonClass: 'bg-[#bd93f9] hover:bg-[#ff79c6] text-[#282a36] font-semibold',
    badgeClass: 'bg-[#44475a] text-[#ff79c6] border-[#bd93f9]/30',
    previewBg: '#282a36',
    previewText: '#f8f8f2',
    cssVars: {
      '--mdxkit-font-body': SANS,
      '--mdxkit-heading-fg': '#ff79c6',
      '--mdxkit-heading-border': '#44475a',
      '--mdxkit-link-fg': '#bd93f9',
      '--mdxkit-inline-code-bg': '#191a21',
      '--mdxkit-inline-code-fg': '#50fa7b',
    },
  },
  nord: {
    id: 'nord',
    name: 'Nord Minimalist',
    category: 'dark',
    fontFamily: 'font-sans',
    bgClass: 'bg-[#2e3440]',
    textClass: 'text-[#eceff4]',
    headingClass: 'text-[#88c0d0] border-b border-[#3b4252]',
    cardBgClass: 'bg-[#3b4252] border-[#434c5e]',
    borderClass: 'border-[#434c5e]',
    codeBgClass: 'bg-[#242933]',
    codeTextClass: 'text-[#a3be8c]',
    accentClass: 'text-[#81a1c1]',
    primaryButtonClass: 'bg-[#88c0d0] hover:bg-[#81a1c1] text-[#2e3440] font-semibold',
    badgeClass: 'bg-[#3b4252] text-[#88c0d0] border-[#81a1c1]/30',
    previewBg: '#2e3440',
    previewText: '#eceff4',
    cssVars: {
      '--mdxkit-font-body': SANS,
      '--mdxkit-heading-fg': '#88c0d0',
      '--mdxkit-heading-border': '#3b4252',
      '--mdxkit-link-fg': '#81a1c1',
      '--mdxkit-inline-code-bg': '#242933',
      '--mdxkit-inline-code-fg': '#a3be8c',
    },
  },
  editorial: {
    id: 'editorial',
    name: 'Warm Editorial',
    category: 'light',
    fontFamily: 'font-serif',
    bgClass: 'bg-[#faf7f2]',
    textClass: 'text-[#2b2621]',
    headingClass: 'text-[#1a1410] border-b border-[#e2dcd3] font-serif',
    cardBgClass: 'bg-[#f3ede3] border-[#e2dcd3]',
    borderClass: 'border-[#e2dcd3]',
    codeBgClass: 'bg-[#eae3d7]',
    codeTextClass: 'text-[#6d28d9]',
    accentClass: 'text-[#9a3412]',
    primaryButtonClass: 'bg-[#9a3412] hover:bg-[#7c2d12] text-amber-50',
    badgeClass: 'bg-[#f3ede3] text-[#9a3412] border-[#9a3412]/30',
    previewBg: '#faf7f2',
    previewText: '#2b2621',
    cssVars: {
      '--mdxkit-font-body': SERIF,
      '--mdxkit-heading-fg': '#1a1410',
      '--mdxkit-heading-border': '#e2dcd3',
      '--mdxkit-heading-font': SERIF,
      '--mdxkit-link-fg': '#9a3412',
      '--mdxkit-inline-code-bg': '#eae3d7',
      '--mdxkit-inline-code-fg': '#6d28d9',
    },
  },
  cyberpunk: {
    id: 'cyberpunk',
    name: 'Cyberpunk Neon',
    category: 'dark',
    fontFamily: 'font-mono',
    bgClass: 'bg-[#090a0f]',
    textClass: 'text-[#00ffcc]',
    headingClass: 'text-[#ff007f] border-b border-[#00ffcc]/30 font-mono tracking-wider',
    cardBgClass: 'bg-[#121526] border-[#ff007f]/40 shadow-[0_0_15px_rgba(255,0,127,0.15)]',
    borderClass: 'border-[#ff007f]/30',
    codeBgClass: 'bg-[#050608]',
    codeTextClass: 'text-[#ffee00]',
    accentClass: 'text-[#ff007f]',
    primaryButtonClass: 'bg-[#ff007f] hover:bg-[#00ffcc] hover:text-black text-white font-mono tracking-wider shadow-[0_0_10px_#ff007f]',
    badgeClass: 'bg-[#ff007f]/20 text-[#00ffcc] border-[#ff007f]',
    previewBg: '#090a0f',
    previewText: '#00ffcc',
    cssVars: {
      '--mdxkit-font-body': MONO,
      '--mdxkit-heading-fg': '#ff007f',
      '--mdxkit-heading-border': 'color-mix(in oklab, #00ffcc 30%, transparent)',
      '--mdxkit-heading-font': MONO,
      '--mdxkit-heading-tracking': '0.05em',
      '--mdxkit-link-fg': '#ff007f',
      '--mdxkit-inline-code-bg': '#050608',
      '--mdxkit-inline-code-fg': '#ffee00',
    },
  },
  forest: {
    id: 'forest',
    name: 'Forest Solitude',
    category: 'dark',
    fontFamily: 'font-sans',
    bgClass: 'bg-[#0f1d17]',
    textClass: 'text-[#d1fae5]',
    headingClass: 'text-[#34d399] border-b border-[#1b382b]',
    cardBgClass: 'bg-[#142920] border-[#1b382b]',
    borderClass: 'border-[#1b382b]',
    codeBgClass: 'bg-[#0a1410]',
    codeTextClass: 'text-[#6ee7b7]',
    accentClass: 'text-[#10b981]',
    primaryButtonClass: 'bg-[#059669] hover:bg-[#10b981] text-emerald-950 font-medium',
    badgeClass: 'bg-[#1b382b] text-[#34d399] border-[#059669]/40',
    previewBg: '#0f1d17',
    previewText: '#d1fae5',
    cssVars: {
      '--mdxkit-font-body': SANS,
      '--mdxkit-heading-fg': '#34d399',
      '--mdxkit-heading-border': '#1b382b',
      '--mdxkit-link-fg': '#10b981',
      '--mdxkit-inline-code-bg': '#0a1410',
      '--mdxkit-inline-code-fg': '#6ee7b7',
    },
  },
};
